modName = ApplyGray

modId = applygray

modGroup = applygray

modVersion = 1.0.0

includeMCVersionJar = true

modArchivesBaseName = applygray

autoUpdateBuildScript = false

minecraftVersion = 1.12.2

developmentEnvironmentUserName = ApplyGrayDev
additionalJavaArguments=

enableModernJavaSyntax = true
enableJava17RunTasks=false

generateGradleTokenClass = applygray.ApplyGrayInternalTags
gradleTokenModId =
gradleTokenModName =
gradleTokenVersion = VERSION

apiPackage =

useSrcApiPath=false

accessTransformersFile =

usesMixins = true
mixinsPackage = mixins
mixinConfigRefmap=
generateMixinConfig = false
coreModClass=mixins.ApplyGrayMixinLoadingPlugin
containsMixinsAndOrCoreModOnly=false

forceEnableMixins=false

enableCoreModDebug=false

includeWellKnownRepositories=true

includeCommonDevEnvMods = true
stripForgeRequirements=false


usesShadowedDependencies = false
minimizeShadowedDependencies = true
relocateShadowedDependencies = true

separateRunDirectories = false

versionDisplayFormat=$MOD_NAME: $VERSION

modrinthProjectId =
modrinthRelations =

curseForgeProjectId =
curseForgeRelations =

releaseType = beta

generateDefaultChangelog = false

noPublishedSources = false
customMavenPublishUrl=
mavenArtifactGroup=

enableSpotless = false

enableJUnit = false

deploymentDebug = false

org.gradle.logging.stacktrace = all
org.gradle.jvmargs = -Xmx3G
